# Generated by Django 2.2.1 on 2019-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20190521_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='chart',
            field=models.CharField(max_length=100, verbose_name='chart'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='locations',
            field=models.CharField(max_length=100, verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='popup',
            field=models.CharField(max_length=100, verbose_name='popup'),
        ),
    ]
