# Generated by Django 2.2.1 on 2019-06-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20190523_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='use_extent',
            field=models.BooleanField(default=True, verbose_name='Use layer extent for map extent'),
        ),
    ]
