# Generated by Django 2.2.1 on 2019-06-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20190611_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='user can download this layer', verbose_name='downloadable'),
        ),
        migrations.AddField(
            model_name='layer',
            name='download_url',
            field=models.URLField(blank=True, help_text='url for download of entire layer', null=True, verbose_name='download url'),
        ),
        migrations.AddField(
            model_name='layer',
            name='stylesheet',
            field=models.URLField(blank=True, help_text='url of stylesheet for GetFeatureInfo response', null=True, verbose_name='stylesheet'),
        ),
    ]
