# Generated by Django 2.2.1 on 2019-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20190616_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeseries',
            options={'verbose_name_plural': 'Timeseries'},
        ),
        migrations.AlterField(
            model_name='layer',
            name='maxzoom',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='maxzoom'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='minzoom',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='minzoom'),
        ),
    ]
