# Generated by Django 2.2.1 on 2019-08-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20190708_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='group')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Map')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'unique_together': {('name', 'map')},
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maps.Group', verbose_name='group'),
            preserve_default=False,
        ),
    ]
