# Generated by Django 2.2.1 on 2019-08-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20190823_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Group', verbose_name='group'),
        ),
    ]
