# Generated by Django 2.2.1 on 2019-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_mirror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='group',
        ),
        migrations.AddField(
            model_name='layer',
            name='group',
            field=models.ManyToManyField(to='maps.Group', verbose_name='group'),
        ),
    ]
