# Generated by Django 2.2.1 on 2019-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20190828_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='group',
            new_name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='layers',
            field=models.ManyToManyField(to='maps.Layer'),
        ),
    ]
