# Generated by Django 2.2.1 on 2019-08-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20190828_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='bbox',
            field=models.CharField(max_length=100, null=True, verbose_name='extent'),
        ),
        migrations.AlterField(
            model_name='group',
            name='layers',
            field=models.ManyToManyField(null=True, to='maps.Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='groups',
            field=models.ManyToManyField(null=True, to='maps.Group', verbose_name='group'),
        ),
    ]
