# Generated by Django 2.2.1 on 2019-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20190830_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='slug',
            field=models.SlugField(default=None, null=True, help_text='Short name for map'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='layers',
            field=models.ManyToManyField(blank=True, to='maps.Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='groups',
            field=models.ManyToManyField(blank=True, to='maps.Group', verbose_name='group'),
        ),
    ]
