# Generated by Django 2.2.1 on 2019-08-31 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_auto_20190830_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='layers',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='groups',
        ),
        migrations.AddField(
            model_name='layer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=models.SlugField(help_text='Short name for map',null=True),
        ),
    ]
