# Generated by Django 2.2.5 on 2019-09-11 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0017_auto_20190831_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0, verbose_name='order')),
                ('visibility', models.BooleanField(default=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Layer', verbose_name='map')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='layer')),
            ],
        ),
    ]
