# Generated by Django 2.2.5 on 2020-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_document_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cluster',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
