# Generated by Django 2.2.5 on 2020-04-01 20:41

from django.db import migrations, models
import django.db.models.deletion
import maps.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_auto_20200330_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='document',
            name='doc',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=maps.models.upload_to_cluster),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maps.DocumentGroup'),
        ),
    ]
