# Generated by Django 2.2.1 on 2019-08-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20190708_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={},
        ),
    ]
