# Generated by Django 2.2.1 on 2019-08-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_auto_20190830_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='bbox',
            field=models.CharField(max_length=100, null=True, verbose_name='extent'),
        ),
    ]
