# Generated by Django 2.2.1 on 2019-09-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_layer_bbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='bbox',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='extent'),
        ),
    ]
